<?php
return array (
  'autogenerated-10-d3d9446802a44259755d38e6d163e820' => 
  array (
    'base' => 'http://localhost:8081/Sites/WIH%20Cement/autogenerated-10',
    'dependencies' => 
    array (
    ),
    'errorHandling' => 
    array (
    ),
    'languages' => 
    array (
      0 => 
      array (
        'title' => 'English',
        'enabled' => true,
        'languageId' => 0,
        'base' => '/',
        'locale' => 'en_US.UTF-8',
        'navigationTitle' => 'English',
        'flag' => 'us',
      ),
    ),
    'rootPageId' => 10,
    'routes' => 
    array (
    ),
  ),
  'autogenerated-11-6512bd43d9caa6e02c990b0a82652dca' => 
  array (
    'base' => 'http://localhost:8081/Sites/WIH%20Cement/autogenerated-11',
    'dependencies' => 
    array (
    ),
    'errorHandling' => 
    array (
    ),
    'languages' => 
    array (
      0 => 
      array (
        'title' => 'English',
        'enabled' => true,
        'languageId' => 0,
        'base' => '/',
        'locale' => 'en_US.UTF-8',
        'navigationTitle' => 'English',
        'flag' => 'us',
      ),
    ),
    'rootPageId' => 11,
    'routes' => 
    array (
    ),
  ),
  'autogenerated-12-c20ad4d76fe97759aa27a0c99bff6710' => 
  array (
    'base' => 'http://localhost:8081/Sites/WIH%20Cement/autogenerated-12',
    'dependencies' => 
    array (
    ),
    'errorHandling' => 
    array (
    ),
    'languages' => 
    array (
      0 => 
      array (
        'title' => 'English',
        'enabled' => true,
        'languageId' => 0,
        'base' => '/',
        'locale' => 'en_US.UTF-8',
        'navigationTitle' => 'English',
        'flag' => 'us',
      ),
    ),
    'rootPageId' => 12,
    'routes' => 
    array (
    ),
  ),
  'autogenerated-2-c81e728d9d4c2f636f067f89cc14862c' => 
  array (
    'base' => 'http://localhost:8081/Sites/WIH%20Cement/autogenerated-2',
    'dependencies' => 
    array (
    ),
    'errorHandling' => 
    array (
    ),
    'languages' => 
    array (
      0 => 
      array (
        'title' => 'English',
        'enabled' => true,
        'languageId' => 0,
        'base' => '/',
        'locale' => 'en_US.UTF-8',
        'navigationTitle' => 'English',
        'flag' => 'us',
      ),
    ),
    'rootPageId' => 2,
    'routes' => 
    array (
    ),
  ),
  'autogenerated-3-eccbc87e4b5ce2fe28308fd9f2a7baf3' => 
  array (
    'base' => 'http://localhost:8081/Sites/WIH%20Cement/autogenerated-3',
    'dependencies' => 
    array (
    ),
    'errorHandling' => 
    array (
    ),
    'languages' => 
    array (
      0 => 
      array (
        'title' => 'English',
        'enabled' => true,
        'languageId' => 0,
        'base' => '/',
        'locale' => 'en_US.UTF-8',
        'navigationTitle' => 'English',
        'flag' => 'us',
      ),
    ),
    'rootPageId' => 3,
    'routes' => 
    array (
    ),
  ),
  'autogenerated-4-a87ff679a2f3e71d9181a67b7542122c' => 
  array (
    'base' => 'http://localhost:8081/Sites/WIH%20Cement/autogenerated-4',
    'dependencies' => 
    array (
    ),
    'errorHandling' => 
    array (
    ),
    'languages' => 
    array (
      0 => 
      array (
        'title' => 'English',
        'enabled' => true,
        'languageId' => 0,
        'base' => '/',
        'locale' => 'en_US.UTF-8',
        'navigationTitle' => 'English',
        'flag' => 'us',
      ),
    ),
    'rootPageId' => 4,
    'routes' => 
    array (
    ),
  ),
  'autogenerated-5-e4da3b7fbbce2345d7772b0674a318d5' => 
  array (
    'base' => 'http://localhost:8081/Sites/WIH%20Cement/autogenerated-5',
    'dependencies' => 
    array (
    ),
    'errorHandling' => 
    array (
    ),
    'languages' => 
    array (
      0 => 
      array (
        'title' => 'English',
        'enabled' => true,
        'languageId' => 0,
        'base' => '/',
        'locale' => 'en_US.UTF-8',
        'navigationTitle' => 'English',
        'flag' => 'us',
      ),
    ),
    'rootPageId' => 5,
    'routes' => 
    array (
    ),
  ),
  'autogenerated-6-1679091c5a880faf6fb5e6087eb1b2dc' => 
  array (
    'base' => 'http://localhost:8081/Sites/WIH%20Cement/autogenerated-6',
    'dependencies' => 
    array (
    ),
    'errorHandling' => 
    array (
    ),
    'languages' => 
    array (
      0 => 
      array (
        'title' => 'English',
        'enabled' => true,
        'languageId' => 0,
        'base' => '/',
        'locale' => 'en_US.UTF-8',
        'navigationTitle' => 'English',
        'flag' => 'us',
      ),
    ),
    'rootPageId' => 6,
    'routes' => 
    array (
    ),
  ),
  'autogenerated-7-8f14e45fceea167a5a36dedd4bea2543' => 
  array (
    'base' => 'http://localhost:8081/Sites/WIH%20Cement/autogenerated-7',
    'dependencies' => 
    array (
    ),
    'errorHandling' => 
    array (
    ),
    'languages' => 
    array (
      0 => 
      array (
        'title' => 'English',
        'enabled' => true,
        'languageId' => 0,
        'base' => '/',
        'locale' => 'en_US.UTF-8',
        'navigationTitle' => 'English',
        'flag' => 'us',
      ),
    ),
    'rootPageId' => 7,
    'routes' => 
    array (
    ),
  ),
  'autogenerated-8-c9f0f895fb98ab9159f51fd0297e236d' => 
  array (
    'base' => 'http://localhost:8081/Sites/WIH%20Cement/autogenerated-8',
    'dependencies' => 
    array (
    ),
    'errorHandling' => 
    array (
    ),
    'languages' => 
    array (
      0 => 
      array (
        'title' => 'English',
        'enabled' => true,
        'languageId' => 0,
        'base' => '/',
        'locale' => 'en_US.UTF-8',
        'navigationTitle' => 'English',
        'flag' => 'us',
      ),
    ),
    'rootPageId' => 8,
    'routes' => 
    array (
    ),
  ),
  'autogenerated-9-45c48cce2e2d7fbdea1afc51c7c6ad26' => 
  array (
    'base' => 'http://localhost:8081/Sites/WIH%20Cement/autogenerated-9',
    'dependencies' => 
    array (
    ),
    'errorHandling' => 
    array (
    ),
    'languages' => 
    array (
      0 => 
      array (
        'title' => 'English',
        'enabled' => true,
        'languageId' => 0,
        'base' => '/',
        'locale' => 'en_US.UTF-8',
        'navigationTitle' => 'English',
        'flag' => 'us',
      ),
    ),
    'rootPageId' => 9,
    'routes' => 
    array (
    ),
  ),
  'main' => 
  array (
    'base' => 'http://localhost:8081/Sites/WIH%20Cement/',
    'dependencies' => 
    array (
      0 => 'typo3/theme-camino',
    ),
    'errorHandling' => 
    array (
    ),
    'languages' => 
    array (
      0 => 
      array (
        'title' => 'English',
        'enabled' => true,
        'languageId' => 0,
        'base' => '/',
        'locale' => 'en_US.UTF-8',
        'navigationTitle' => 'English',
        'flag' => 'us',
      ),
    ),
    'rootPageId' => 1,
    'routes' => 
    array (
    ),
  ),
);
#